from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    # Identify the user sending the message
    user_id: str

    # The message sent by the user
    message: str

class ChatResponse(BaseModel):
    # The response generated by the AI assistant
    reply: str

class CarSearchFilters(BaseModel):
    # Car manufacturer, such as Ford or Toyota
    make: str | None = None

    # Car model, such as Explorer or Corolla
    model: str | None = None

    # Earliest and latest acceptable model year
    min_year: int | None = None

    max_year: int | None = None

    # Maximum total cash price in AED
    max_cash_price: int | None = None

    # Features or terms to search in the title and description
    keywords: list[str] = Field(default_factory=list)